### ISSUE TITLE
test failures on s390x

### ISSUE THREAD

**Issue by davide125** [mdlayher/netlink#201] opened 2022-10-06 16:05 UTC
When building this library on s390x in Fedora a couple of the tests fail:

```
      testing: github.com/mdlayher/netlink
github.com/mdlayher/netlink
--- FAIL: TestIntegrationConnStrict (0.00s)
    conn_linux_integration_test.go:868: socket option 11 was not set to true
    conn_linux_integration_test.go:868: socket option 12 was not set to true
--- FAIL: ExampleAttributeEncoder_encode (0.00s)
got:
netlink attributes:
00000000  00 06 00 01 00 01 00 00  00 10 00 02 68 65 6c 6c  |............hell|
00000010  6f 20 77 6f 72 6c 64 00  00 14 80 03 00 08 00 01  |o world.........|
00000020  00 00 00 02 00 08 00 02  00 00 00 03              |............|
want:
netlink attributes:
00000000  06 00 01 00 01 00 00 00  10 00 02 00 68 65 6c 6c  |............hell|
00000010  6f 20 77 6f 72 6c 64 00  14 00 03 80 08 00 01 00  |o world.........|
00000020  02 00 00 00 08 00 02 00  03 00 00 00              |............|
FAIL
exit status 1
FAIL	github.com/mdlayher/netlink	1.430s
```

See https://koji.fedoraproject.org/koji/taskinfo?taskID=92705006 for the full log (look at build.log).

**Comment by mdlayher** [comment] 2022-10-07 14:42
Thanks for that. The example should be pretty easy to fix. As for the socket options, that is a strange one that I'll have to look into.

**Comment by CyrilBrulebois** [comment] 2022-12-10 13:44
Joining the fun here since @stapelberg was kind enough to point this issue from the nftables one: I can confirm the [test failures on s390x on the Debian CI infrastructure](https://ci.debian.net/packages/g/golang-github-mdlayher-netlink/) as well.

At first glance, there are at least a few trivial byte swaps (since that's a big-endian system).

**Comment by mdlayher** [comment] 2022-12-11 21:59
I'm working to set up an s390x VM but please keep in mind this is a hobby project and lower priority than my daily work.

In the meantime I would guess that the library works correctly but the tests just make more assumptions about endianness than I had assumed.

**Comment by CyrilBrulebois** [comment] 2022-12-11 22:22
Thanks a lot for exploring this, @mdlayher. I totally understand the “hobby” approach (I've been in FLOSS for many years), and knowing that the library itself is believed to be working fine, and that tests might need some improvements on their own, is very interesting! Having that input makes it easier for maintainers to ignore failures on this and that arch (otherwise, doing so blindly might look like shoving bugs under a carpet).

**Comment by mdlayher** [comment] 2022-12-11 23:16
For sure, thanks for understanding!

**Comment by mdlayher** [comment] 2022-12-12 03:54
I poked around at this a bit tonight (getting the VM running was easier than I thought) and I've fixed one test and skipped another that relies on little endian byte dumps. I would expect current HEAD to pass, and the version you're packaging only had bugs in tests.

I'm going to close this out and will make a new release in the next day or two!

**Closed by mdlayher** 2022-12-12 03:54 UTC

**Comment by CyrilBrulebois** [comment] 2022-12-14 00:33
This was packaged swiftly by Daniel Swarbrick and while it hasn't been picked up by https://ci.debian.net/ just yet, I've just built/tested it successfully on s390x. Thanks!
