### ISSUE TITLE
Invalid sequence number for dump messages

### ISSUE THREAD

**Issue by bluecmd** [mdlayher/netlink#108] opened 2018-09-09 14:27 UTC
Hi,

I'm using genetlink and netlink, but my feeling is that the issue is more generic than genetlink, so I'm putting the issue here.

I have this code:
```
	c, err := genetlink.Dial(nil)
	if err != nil {
		log.Fatalf("dial generic netlink: %v", err)
	}
	defer c.Close()

	family, err := c.GetFamily("NCSI")
	if err != nil {
		log.Fatalf("get NCSI netlink family: %v", err)
	}
	// [ .. ]
	for {
		req := genetlink.Message{
				Header: genetlink.Header{
					Command: NCSI_CMD_PKG_INFO,
					Version: family.Version,
				},
			Data: ed,
		}

		msgs, err := c.Execute(req, family.ID, netlink.HeaderFlagsRequest |  netlink.HeaderFlagsDump)
		if err != nil {
			log.Fatalf("execute NCSI dump: %v", err)
		}

		log.Printf("got %v replies", len(msgs))

		for _, m := range msgs {
			ad, err := netlink.NewAttributeDecoder(m.Data)
			if err != nil {
				log.Fatalf("failed to create attribute decoder: %v", err)
			}
			for ad.Next() {
				if ad.Type() == NCSI_ATTR_PACKAGE_LIST {
					handleNcsiPackageList(ad.Bytes())
				}
			}
		}
		time.Sleep(5 * time.Second)
	}
```

And that results in the first round being processed OK, but the second crashing with:
```
1970/01/01 00:00:13 execute NCSI dump: mismatched sequence in netlink reply
```

Adding some traces in the library and the kernel results in:
```
1970/01/01 00:00:13 nextSequence called, a4d861bd is the new value
1970/01/01 00:00:13 MarshalBinary working on sequence a4d861bd
[   13.147538] DEBUG: netlink_rcv_skb sequence is a4d861bd
[   13.153799] DEBUG: ncsi_pkg_info_all_nl sequence is a4d861bc
[   13.159327] DEBUG: ncsi_pkg_info_all_nl sequence is a4d861bc
1970/01/01 00:00:13 request has sequence a4d861bd
1970/01/01 00:00:13 reply has sequence a4d861bc
1970/01/01 00:00:13 expected a4d861bd, got a4d861bc
1970/01/01 00:00:13 execute NCSI dump: mismatched sequence in netlink reply
```

These are the traces I added in the kernel:
```
diff --git a/net/ncsi/ncsi-netlink.c b/net/ncsi/ncsi-netlink.c
index 82e6edf9c5d9..f0eb130631d5 100644
--- a/net/ncsi/ncsi-netlink.c
+++ b/net/ncsi/ncsi-netlink.c
@@ -216,6 +216,8 @@ static int ncsi_pkg_info_all_nl(struct sk_buff *skb,
 	void *hdr;
 	int rc;
 
+  printk("DEBUG: ncsi_pkg_info_all_nl sequence is %08x\n", cb->nlh->nlmsg_seq);
+
 	rc = genlmsg_parse(cb->nlh, &ncsi_genl_family, attrs, NCSI_ATTR_MAX,
 			   ncsi_genl_policy, NULL);
 	if (rc)
diff --git a/net/netlink/af_netlink.c b/net/netlink/af_netlink.c
index 13a203157dbe..7d82aa274b45 100644
--- a/net/netlink/af_netlink.c
+++ b/net/netlink/af_netlink.c
@@ -2448,6 +2448,8 @@ int netlink_rcv_skb(struct sk_buff *skb, int (*cb)(struct sk_buff *,
 		if (!(nlh->nlmsg_flags & NLM_F_REQUEST))
 			goto ack;
 
+    printk(KERN_ERR "DEBUG: netlink_rcv_skb sequence is %08x\n", nlh->nlmsg_seq);
+
 		/* Skip control messages */
 		if (nlh->nlmsg_type < NLMSG_MIN_TYPE)
 			goto ack;
```

These are in the netlink library:

```

diff --git a/conn.go b/conn.go
index d2dffb3..b7d987f 100644
--- a/conn.go
+++ b/conn.go
@@ -3,6 +3,7 @@ package netlink
 import (
        "errors"
        "io"
+       "log"
        "math/rand"
        "os"
        "sync/atomic"
@@ -500,17 +501,22 @@ func (rc *rawConn) Write(_ func(fd uintptr) (done bool)) error { return errSysca
 // nextSequence atomically increments Conn's sequence number and returns
 // the incremented value.
 func (c *Conn) nextSequence() uint32 {
-       return atomic.AddUint32(c.seq, 1)
+       n := atomic.AddUint32(c.seq, 1)
+       log.Printf("nextSequence called, %08x is the new value", n)
+       return n
 }
 
 // Validate validates one or more reply Messages against a request Message,
 // ensuring that they contain matching sequence numbers and PIDs.
 func Validate(request Message, replies []Message) error {
+       log.Printf("request has sequence %08x", request.Header.Sequence)
        for _, m := range replies {
                // Check for mismatched sequence, unless:
                //   - request had no sequence, meaning we are probably validating
                //     a multicast reply
+               log.Printf("reply has sequence %08x", m.Header.Sequence)
                if m.Header.Sequence != request.Header.Sequence && request.Header.Sequence != 0 {
+                       log.Printf("expected %08x, got %08x", request.Header.Sequence, m.Header.Sequence)
                        return errMismatchedSequence
                }
 
diff --git a/message.go b/message.go
index 8cd514d..3197ffd 100644
--- a/message.go
+++ b/message.go
@@ -3,6 +3,7 @@ package netlink
 import (
        "errors"
        "fmt"
+       "log"
 
        "github.com/mdlayher/netlink/nlenc"
 )
@@ -199,6 +200,7 @@ func (m Message) MarshalBinary() ([]byte, error) {
        nlenc.PutUint16(b[4:6], uint16(m.Header.Type))
        nlenc.PutUint16(b[6:8], uint16(m.Header.Flags))
        nlenc.PutUint32(b[8:12], m.Header.Sequence)
+       log.Printf("MarshalBinary working on sequence %08x\n", m.Header.Sequence)
        nlenc.PutUint32(b[12:16], m.Header.PID)
        copy(b[16:], m.Data)

````

It looks like the kernel passes the old sequence number from my previous request to the dump function when called the second time.

So this looks like either in order of probability:

- My code is doing something I'm not allowed to, or I'm not handling the dump correctly
- There is a bug in the netlink library when doing multiple dumps on a single connection
- The NCSI netlink family in the kernel is bugged

Do you have any idea? I've been scratching my head at this for a few hours now.

**Comment by mdlayher** [comment] 2018-09-09 15:44
Interesting! I'm not familiar with this family, but I would suggest calling Send and Receive manually for the time being to circumvent the check.

I'll take a look at this tomorrow and hopefully have an answer for you this week.

**Comment by ti-mo** [comment] 2018-09-09 20:09
I'm not familiar with genetlink, but this commit seems like it could have an impact on this behaviour on the kernel side: https://github.com/torvalds/linux/commit/3d0371b313b84ba7c16ebf2526a7a34f1c57b19e.

As your tracing shows, the kernel indeed responds with the wrong sequence.

**Comment by bluecmd** [comment] 2018-09-09 20:47
Applied and verified! That fixes the issue. Thanks so much for the speedy help :-)

**Comment by ti-mo** [comment] 2018-09-10 07:29
Great, thanks for reporting back! Feel free to close the issue.

**Closed** 2018-09-10 07:36 UTC

**Comment by mdlayher** [comment] 2018-09-10 14:32
Interesting! Glad you both were able to work this out. If this ends up being a bug in my package in some form though, please do report back.

**Comment by bduffany** [comment] 2023-06-02 02:23
I ran into this problem here https://github.com/Merovius/nbd/issues/18 ("NBD" family), and also found [this SO thread](https://stackoverflow.com/questions/51370678/netlink-sequence-numbers-out-of-sequence) where someone using the "MAC80211_HWSIM" family also hit this problem.

Maybe the netlink protocol forbids this, but is it possible that the repeated sequence number in the recv is a "second reply" to the request with that original sequence number?

**Comment by mdlayher** [comment] 2023-06-02 13:07
No idea sorry. If you run into a family that doesn't behave as normal, you can swap calls to Execute with Send/Receive though to handle it.

**Comment by bduffany** [comment] 2023-06-04 19:39
So after some debugging, the two replies in my case seemed to be caused by setting the `Acknowledge` flag. Unsetting that flag fixed the issue.

In my case, a reply is sent by the driver here: https://github.com/torvalds/linux/blob/9561de3a55bed6bdd44a12820ba81ec416e705a7/drivers/block/nbd.c#L2449
but then because of the `Acknowledge` flag, this logic would also kick in and send another reply: https://github.com/torvalds/linux/blob/9561de3a55bed6bdd44a12820ba81ec416e705a7/net/netlink/af_netlink.c#L2551-L2552

Confusingly, some requests for the NBD driver return replies using `genlmsg_put_reply` (and therefore ACK doesn't need to be set), and others don't (which require ACK if you want to use `Execute()`). 

Maybe the `Acknowledge` flag documentation could use some clarification on when to use it? Something like:
- If you try `Execute()` and it hangs while waiting for a recv, you probably need to set the `Acknowledge` flag to force a reply.
- Otherwise, you probably shouldn't set the acknowledge flag.

Or maybe I am completely misunderstanding all of this :sweat_smile:

But if this sounds good, I'm happy to send a PR
