### ISSUE TITLE
Signal block while Receiving

### ISSUE THREAD

**Issue by MXWXZ** [mdlayher/netlink#168] opened 2020-06-09 16:54 UTC
Hi, I found that when I call `Receive`, system signal is blocked(such as `syscall.SIGINT` and `syscall.SIGTERM`. However I need to support interrupt when nothing received(like `ctrl+c`). How could I do?

**Comment by mdlayher** [comment] 2020-06-09 17:00
The following program works with no problems:

```go
package main

import (
	"log"

	"github.com/mdlayher/netlink"
	"golang.org/x/sys/unix"
)

func main() {
	c, err := netlink.Dial(unix.NETLINK_ROUTE, nil)
	if err != nil {
		log.Fatalf("failed to dial: %v", err)
	}
	defer c.Close()

	for {
		msgs, err := c.Receive()
		if err != nil {
			log.Fatalf("failed to receive: %v", err)
		}

		log.Println(msgs)
	}
}
```

```
✔ ~/src/github.com/mdlayher/netlink/cmd/nlblock [master|…1] 
12:59 $ ./nlblock 
^C
✘-INT ~/src/github.com/mdlayher/netlink/cmd/nlblock [master|…1] 
```

What exactly are you trying to do? Can you provide example code?

**Comment by MXWXZ** [comment] 2020-06-09 17:04
> The following program works with no problems:
> 
> ```go
> package main
> 
> import (
> 	"log"
> 
> 	"github.com/mdlayher/netlink"
> 	"golang.org/x/sys/unix"
> )
> 
> func main() {
> 	c, err := netlink.Dial(unix.NETLINK_ROUTE, nil)
> 	if err != nil {
> 		log.Fatalf("failed to dial: %v", err)
> 	}
> 	defer c.Close()
> 
> 	for {
> 		msgs, err := c.Receive()
> 		if err != nil {
> 			log.Fatalf("failed to receive: %v", err)
> 		}
> 
> 		log.Println(msgs)
> 	}
> }
> ```
> 
> ```
> ✔ ~/src/github.com/mdlayher/netlink/cmd/nlblock [master|…1] 
> 12:59 $ ./nlblock 
> ^C
> ✘-INT ~/src/github.com/mdlayher/netlink/cmd/nlblock [master|…1] 
> ```
> 
> What exactly are you trying to do? Can you provide example code?

I need to handle some cleanup code so I capture the signal like this 
```
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/mdlayher/netlink"
	"golang.org/x/sys/unix"
)

func main() {
	c, err := netlink.Dial(unix.NETLINK_ROUTE, nil)
	if err != nil {
		log.Fatalf("failed to dial: %v", err)
	}
	defer c.Close()

	s := make(chan os.Signal, 1)
	signal.Notify(s, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-s
		c.Close()
		os.Exit(0)
	}()

	for {
		msgs, err := c.Receive()
		if err != nil {
			log.Fatalf("failed to receive: %v", err)
		}

		log.Println(msgs)
	}
}
```
This will lead to dead loop.

**Comment by mdlayher** [comment] 2020-06-09 17:05
This is a duplicate of #162, so closing.

**Closed by mdlayher** 2020-06-09 17:05 UTC
